# Funding configuration
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [openlysts]
custom:
  - "https://paypal.me/buymegoodcoffee/sponsor"
  - "https://openlysts.dpdns.org/sponsor"
